# SPDX-License-Identifier: MIT
# Copyright © 2025 Bijan Mousavi

from typing import Any, Iterator

def packb(o: Any, **kwargs: Any) -> bytes: ...
def unpackb(data: bytes, **kwargs: Any) -> Any: ...

class Unpacker:
    def __init__(self, stream: Any = ..., **kwargs: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def read_bytes(self, n: int) -> bytes: ...
    def feed(self, data: bytes) -> None: ...
    def __next__(self) -> Any: ...
